server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: clustered-search-and-indexing-engine

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  flyway:
    enabled: false # for now not needed, TO-DO: look in DB compatibility
    baseline-on-migrate: true
    # ignore-migration-patterns: '*:unsupported'
    # validateOnMigrate: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

engine:
  indexPath: ${ENGINE_INDEX_PATH}

management:
  server:
    port: ${MANAGEMENT_PORT}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${MANAGEMENT_METRICS_TAG}

security:
  jwt:
    hmacSecret: ${JWT_HMAC_BASE64}
    ttlSeconds: ${JWT_TTL_SECONDS}
    secret: ${JWT_SECRET}

grpc:
  server:
    port: ${GRPC_PORT}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
